name: parking_system
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_bloc: ^8.1.3
  uuid: ^4.1.0
  loading_animation_widget: ^1.2.0+4
  mockito: ^5.3.2
  build_runner: ^2.2.0
  http_mock_adapter: ^0.4.4

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/data/
    - assets/data/parkingModel.json


  uses-material-design: true

  


